baseURL = "https://fuu.margot.maison"
title = "sickcallfuu"
author = "margot ferrick"
email = "m@margot.maison"
languageCode = "en-US"

[params]
  subtitle = "my fromsoft fanart"
  dateFmt = "2006-01-02"
  ShowDatesOnPosts = true
  mainSections = "post"
  enableEmoji = true
  favicon="images/favicon.ico"
  summaryLength = 70
  imageCdn = "https://cdn.margot.maison/fuu/"
  staticDir = ['assets', 'static']
  assetDir = 'assets/'

[pagination]
  pagersize = 50

[menus]
  [[menus.main]]
    name = 'Elden Ring'
    pageRef = '/eldenring'
    weight = 10
  [[menus.main]]
    name = '[R-18] Elden Ring'
    pageRef = '/r18-eldenring'
    weight = 20
  [[menus.main]]
    name = 'Dark Souls'
    pageRef = '/darksouls'
    weight = 30
  [[menus.main]]
    name = '[R-18] Dark Souls'
    pageRef = '/r18-darksouls'
    weight = 40
  [[menus.main]]
    name = 'Comics'
    pageRef = '/comics'
    weight = 50
  [[menus.main]]
    name = 'blog'
    pageRef = '/post'
    weight = 60

[taxonomies]
  tag = "tags"
  catergory = "categories"

[outputs]
  home = ["html","rss"]
  section = ["html","rss"]
  taxonomy = ["html","rss"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "index"
